apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    tagetPort: 80
  selector:
    app: ngin
  type: NodePort
